apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gazelle-python 
  janus-idp.io/tekton: gazelle-python
  backstage.io/kubernetes-id: gazelle-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gazelle-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  